/* config-keepassx-tests.h. Generated by cmake from config-keepassx-tests.h.cmake */

#ifndef KEEPASSX_CONFIG_TESTS_H
#define KEEPASSX_CONFIG_TESTS_H

#define KEEPASSX_TEST_DATA_DIR "${KEEPASSX_TEST_DATA_DIR}"
#define GOOGLE_DRIVE_SYNC "${WITH_GOOGLE_DRIVE}"

#endif // KEEPASSX_CONFIG_TESTS_H
