#ifndef ERRORS_H
#define ERRORS_H
class Errors
{
public:
    enum {NO_ERROR = 0};
    enum SyncError {AMBIGIOUS_DB=1,NETWORK_PROBLEM=2,SYNC_PROBLEM=3,KEY_PROBLEM=4};
    enum DownloadError {COMMON_DOWNLOAD_PROBLEM=21, DBNAME_ERROR_PROBLEM=22, GOOGLEDRIVEAPI_DOWNLOAD_COMMAND_PROBLEM=23};
    enum FileError {OPEN_FILE_PROBLEM=41};
    enum AuthorizationError {GENERAL_AUTH_PROBLEM = 60, USER_APPROVE_PROBLEM = 61};
    Errors();
};

#endif // ERRORS_H
