#!/bin/bash
BUILD_FOLDER=release
CPUCOUNT=`awk '/processor/{i++}END{print i}' /proc/cpuinfo`
[ ! -d $BUILD_FOLDER ] && mkdir $BUILD_FOLDER
pushd $BUILD_FOLDER
cmake -DCMAKE_BUILD_TYPE=Release ..
make -j $CPUCOUNT
popd
